### ISSUE TITLE
[BUG] Input looks weird in dark mode

### ISSUE THREAD

**Issue by rfoel** [Gympass/yoga#119]
**Describe the bug**
All inputs have incorrect styling in dark mode. Specially the label and focus/active style.

**Expected behavior**
Correct style for dark mode.

**Screenshots**

![image](https://user-images.githubusercontent.com/19496473/75986293-9129da80-5ecc-11ea-8a26-1e2715796284.png)

![image](https://user-images.githubusercontent.com/19496473/75986494-efef5400-5ecc-11ea-8024-9b3cb1004eee.png)

**Comment by victormath12** [comment]
hello @rfoel, what's up?

Thank you for this Issue.

All components are developed to work in mapped scenarios, when we have cases that some component should be applied on colorful background we develop and test this component to work well in this scenario. 

In the case of Input component we don't consider that it should be applied on colored backgrounds (including dark mode), if you consider that will be necessary to you or your team let us know!

**Comment by allyssonsantos** [comment]
@rfoel We fixed this weird behavior on web platform with this PR #122, I didn't figure it out how to fix this in native platform yet.
