### ISSUE TITLE
[BUG] Dropdown background is white while Input background is transparent

### ISSUE THREAD

**Issue by tsuzukayama** [Gympass/yoga#129]
**Describe the bug**

The dropdown component has a white background, while the Input component has a transparent background. This can lead to inconsistencies on design.

**To Reproduce**
1.Create a dropdown component with dark background
2. Create a Input component with dark background
3. See the diference

**Expected behavior**
Form components should have a design consistency

**Screenshots**

##### Dropdown

![image](https://user-images.githubusercontent.com/5157800/76881426-df899280-6857-11ea-9c6b-4206def8fb87.png)

##### Input 

![image](https://user-images.githubusercontent.com/5157800/76881457-eb755480-6857-11ea-9ab4-7d4481747fd2.png)

**Comment by tsuzukayama** [comment]
@victormath12

**Comment by geovanasilva** [comment]
I believe that the dropdown component doesn't need to be the same as the input, allowing it to be completely transparent on a dark background breaks the visual aesthetics of the dropdown itself. Anyway, I started this conversation in the group with the responsible designer and we both agreed that it should remain as it is, so I'm closing this issue.
