### ISSUE TITLE
[BUG] Dropdown selection is not cleareable

### ISSUE THREAD

**Issue by tsuzukayama** [Gympass/yoga#130]
**Describe the bug**
Once I select a value from the dropdown component, I can't clear it, making it unable to have empty values.

**To Reproduce**
1. Create a dropdown component
2. Select a value
3. Try to unselect it

**Expected behavior**
Be able to clear dropdown selection

**Comment by willianwelbert** [comment]
I've just crossed this scenario again in a bug, caused a little confusion since the value of the input field is not directly controllable.
