### ISSUE TITLE
[FEAT] Make `label` and `placeholder` props excluded on Input and TextArea

### ISSUE THREAD

**Issue by tcK1** [Gympass/yoga#196]
**Is your feature request related to a problem? Please describe.**
Although this is not a bug, since we users can be on the lookout, it seems weird to be able to use both props at the same time, following are examples of what it looks like:

*Input*:
![image](https://user-images.githubusercontent.com/9873486/101013247-bffbdc80-3542-11eb-8e34-0690a1e6d580.png)
![image](https://user-images.githubusercontent.com/9873486/101013394-fb96a680-3542-11eb-9b6c-ab5e0b626c4d.png)

*TextArea*:
![image](https://user-images.githubusercontent.com/9873486/101013312-dc981480-3542-11eb-8209-9b08a4d50a37.png)
![image](https://user-images.githubusercontent.com/9873486/101013332-e3bf2280-3542-11eb-812b-1cd328c58ba3.png)

**Describe the solution you'd like**
I guess we have two choices:

1. Throw and error when trying to use both props at the same time. This will "guide" the use as how it should use the component; How we intended it to be used.
2. If this is a behaviour that we want, we should only show the placeholder when the component has focus, that way we do not overlap the texts.

**Describe alternatives you've considered**
At the moment none, since we have always needed one or the other.

If I were to use both, I would probably add the `onFocus` handler myself.

**Comment by allyssonsantos** [comment]
Hi @tcK1, thank you for opening this issue!

We've talked with the PD responsible for the design rules and she will think on how it should work.
If we need the both behaviors, just `Label, just `placeholder`, etc.

 I will let you know when we have something more assertive about it.

**Comment by ricardomalan** [comment]
Hi @tcK1, I created a PR solving this issue. #429
