### ISSUE TITLE
[DOCS] Make CONTRIBUTING.md more evident

### ISSUE THREAD

**Issue by evilamaior** [Gympass/yoga#206]
What do you think about making "[CONTRIBUTING](https://github.com/Gympass/yoga/blob/master/CONTRIBUTING.md)" more evident? I was a little lost on how to contribute and took me a while to find the link. Maybe, it's good to have this help in the [root README](https://github.com/Gympass/yoga) or a clearer hyperlink. What do you think of [this example](https://github.com/facebook/react#contributing)?

**Comment by coelhucas** [comment]
As I talked with @evilamaior, we believe this can be closed after #219.
