### ISSUE TITLE
[FEAT] Update Theme section on `CONTRIBUTING.md`

### ISSUE THREAD

**Issue by tcK1** [Gympass/yoga#260]
We should update the Theme section at https://github.com/Gympass/yoga/blob/master/CONTRIBUTING.md#theme file, to how it is now (only one theme).

**Comment by coelhucas** [comment]
I'm going to fix this within #344

**Comment by ggdaltoso** [comment]
@coelhucas 

Was this issue solved by #344?

**Comment by coelhucas** [comment]
I believe so, we have it now under the [`#theming`](https://github.com/Gympass/yoga/blob/master/CONTRIBUTING.md#theming) anchor. 😉
