### ISSUE TITLE
[BUG] Checkbox not keeping width with large text label

### ISSUE THREAD

**Issue by dehmirandac2** [Gympass/yoga#279]
**Describe the bug**

The Checkbox component is not keeping the width when the label text is large

**To Reproduce**
1. Go to https://gympass.github.io/yoga/components/checkbox/default
2. Edit the component adding a large label text
3. Check if the checkbox is with a wrong width

**Expected behavior**
When I add a large label text I expect that checkbox keep the width defined

**Screenshots**
![Screenshot from 2021-06-29 10-09-42](https://user-images.githubusercontent.com/8313529/123803112-608c6200-d8c2-11eb-968b-85b739de43ac.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome
 - Version: 86.0

**Comment by ggdaltoso** [comment]
OMG!

Thanks for getting into this!

Are you willing to solve this issue?

**Comment by dehmirandac2** [comment]
> OMG!
> 
> Thanks for getting into this!
> 
> Are you willing to solve this issue?

Yep! I'll solve this issue
