### ISSUE TITLE
[BUG] PlanCard does not have dynamic height according to ListItem quantity

### ISSUE THREAD

**Issue by alycecristines** [Gympass/yoga#281]
**Describe the bug**
When we enter more than 3 PlanCard.ListItem these items overlap the contents below them, as the PlanCard does not have a dynamic height, its height is currently fixedly defined.

**To Reproduce**
1. Go to [https://gympass.github.io/yoga/components/card/plancard](https://gympass.github.io/yoga/components/card/plancard)
2. Edit the component adding more than 3 PlanCard.ListItem
3. See that the listItems are overlaping the content below them

**Expected behavior**
It is expected that the PlanCard size is adjusted according to the number of items on the list, respecting the spacing defined in the figma prototype

**Screenshots**
<img alt="android screenshot" src="https://user-images.githubusercontent.com/44280864/123837905-c20ff900-d8e1-11eb-8449-5d0eb42b69ae.png" width="312" />

**Desktop:**
 - OS: `all`
 - Browser `all`
 - Version `all`

**Smartphone:**
 - Device: `all`
 - OS: `all`
 - Browser `all`
 - Version `all`

**Comment by ggdaltoso** [comment]
Another issue today!

Thanks for getting into this, @alycecristines!

Do you want to contribute by solving this issue?

**Comment by alycecristines** [comment]
> Another issue today!
> 
> Thanks for getting into this, @alycecristines!
> 
> Do you want to contribute by solving this issue?

yes 😊
