### ISSUE TITLE
[BUG] Badge on readme

### ISSUE THREAD

**Issue by alan-oliv** [Gympass/yoga#330]
All contributors badge on [readme.md](https://github.com/Gympass/yoga/blob/master/README.md) is a hardcoded badge and says that only **4** people contributed to _Yoga_

The badge should reflect the real number of contributors, or we should remove the this info

**Screenshots**
![image](https://user-images.githubusercontent.com/4368481/131578140-0c39404b-719f-4b05-821e-0a30986cc72a.png)

**Comment by ggdaltoso** [comment]
It seems to be an easy fix

ref: https://allcontributors.org/docs/en/bot/faq#all-contributors-badge-count-does-not-update

Would you like to do it?

**Comment by marcosricardo** [comment]
I can do it!
