### ISSUE TITLE
[FEAT] WEB: Make Button and Button.Link the same component

### ISSUE THREAD

**Issue by coelhucas** [Gympass/yoga#360]
**Is your feature request related to a problem? Please describe.**
Button could be smart enough to work as a link too. Se more about in [this](https://twitter.com/claviska/status/1445479402532261892) twitter thread that @ggdaltoso recently sent me.

**Describe the solution you'd like**
Given 
`<Button href="https://google.com" />` 
Our button should be smart enough to render this:
`<a href="https://google.com" />`

While given a
`<Button onClick={() => {}}>Hey there!</Button>`
It should do the usual, as.:
`<button onClick={() =>{}}>Hey there!</button>`

**Describe alternatives you've considered**
It requires minor changes in `web/button` of Yoga package to solve it and drop `Button.Link`
The main cons I see here is not having the same API in Native, but since native doesn't have the concept of anchor tag, it makes sense to be different.

**Comment by Wendlereis** [comment]
This is related to #447
