### ISSUE TITLE
[FEAT] Add search launch

### ISSUE THREAD

**Issue by mmartinsoliv** [Gympass/yoga#367]
**Is your feature request related to a problem? Please describe.**
It doesn't relate to a problem, but it's a suggestion to make it easier to find components and information in the documentation.

Search launch example: 

![image](https://user-images.githubusercontent.com/46993493/136603032-422f4717-10a3-44aa-b990-e928f3dc9b43.png)

Ref: https://ant.design/docs/react/introduce

**Comment by coelhucas** [comment]
I second this! Anyone wanting to know more about that, look for [kbar](https://css-tricks.com/kbar/)
This is also opened by <kbd>⌘</kbd> + <kbd>K</kbd>
