### ISSUE TITLE
[BUG] Avatar image flickering on android when using prop `children`

### ISSUE THREAD

**Issue by alycecristines** [Gympass/yoga#379]
**Describe the bug**
when trying to use the new avatar feature using `react-native-fast-image` as prop `children` we have a image flickering behavior on android.

**To Reproduce**
1. Go to new explore screen (on gympass app)
2. See error (images flickering)

**Expected behavior**
Expeted the images to not be flickering when using `react-native-fast-image`

**Screenshots**
`not applicable`

**Desktop (please complete the following information):**
`not applicable`

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: > 9.0

**Screenshot**
<img alt="flickering" src="https://user-images.githubusercontent.com/44280864/140403294-cd89a001-d1e5-415d-a109-4c89f163bde4.gif" width="340" />

**Additional context**
`not applicable`

**Comment by coelhucas** [comment]
I believe that videos/gifs are applicable here if possible to give us additional context
