### ISSUE TITLE
[BUG] Anchoring doesn't properly works in pages with tabs

### ISSUE THREAD

**Issue by coelhucas** [gympass/yoga#392]
**Describe the bug**
We can't get an anchor links to "titles" inside tabs other than the default one

**To Reproduce**
1. Go to some section inside a tab that isn't the default one, such as "React Native > 0.60" inside [Components Getting Started](https://gympass.github.io/yoga/components/getting-started/),  and click its anchor:
![image](https://user-images.githubusercontent.com/28108272/141162180-863798f8-7cd6-4fb2-9b93-805ff648e4b9.png)
**Result url:** https://gympass.github.io/yoga/components/getting-started#react-native--060

2. You'll be redirected to the main tab, since each tab is by itself already an anchor (such as `#native`)
![image](https://user-images.githubusercontent.com/28108272/141162425-cc3812f1-978a-417e-bca5-7a079625ec1a.png)

**Expected behavior**
We should be able to "inherit" a tab inside our anchor in order to copy a direct link to a section rather to just the tab itself. We can open a page with a default tab, such as [components/getting-started#native](https://gympass.github.io/yoga/components/getting-started#native), but we can't link any other anchor inside this tab to be opened in.

**Additional context**
Other sites such as React Native's documentation for instance support an anchor direct to its title and it will infer the correct tab to be opened. In case of "conflicting" anchors, such as `Adding Gympass font in your project` that we have in both Android and iOS, they send you to the default one (Android)

See [here](https://reactnative.dev/docs/environment-setup#development-os) for instance an example that will send you to the React Native CLI tab instead of the default one (Expo)

**Comment by caiotracera** [comment]
Hey @coelhucas,

Hope you're doing well! 🌟
Just wanted to give you a heads-up that it seems like this issue has taken a bit of a nap and gone MIA. 😴 Since we're doing some cleanup, we're going to close it for now.

No worries though! If you think there's still life in it or if you've got more info to share, feel free to wake it up by reopening. Your input is always appreciated!
