### ISSUE TITLE
[BUG] Cannot have selected option with dynamic data (Dropdown component)

### ISSUE THREAD

**Issue by dehmirandac2** [gympass/yoga#445]
**Describe the bug**
When mounting the [Dropdown](https://gympass.github.io/yoga/components/dropdown) component with dynamic data (coming from an API, for instance) it's not possible to set the `selected` value.

I'm rendering the following component with the dynamic as shown bellow:
<img width="1004" alt="Screen Shot 2022-02-22 at 15 19 14" src="https://user-images.githubusercontent.com/8313529/155194499-5ded6ff2-312d-425f-84fa-a95e6e8bfb33.png">

The component is not setting the Minas Gerais value as the select one, even if we are adding the selected flag as true
<img width="365" alt="Screen Shot 2022-02-22 at 15 03 40" src="https://user-images.githubusercontent.com/8313529/155192683-f7a560e2-db68-4eee-8389-b5eefd7aa18d.png">

But as you can see in the following print, the first render of the Dropdown component is with an empty array, because this list will be filled only after the API response
<img width="1015" alt="Screen Shot 2022-02-22 at 15 09 42" src="https://user-images.githubusercontent.com/8313529/155194053-a4df30fd-2f2f-4c74-a161-6ce26cac1f35.png">

**Expected behavior**
When adding the same data hardcoded the Dropdown component works fine

Component after the first load, with the right selected value:
<img width="375" alt="Screen Shot 2022-02-22 at 15 06 08" src="https://user-images.githubusercontent.com/8313529/155194754-48269de3-ca78-4bc9-8bf7-a63d59d98c1c.png">

Hardcoded array with the selected value:
<img width="523" alt="Screen Shot 2022-02-22 at 15 06 25" src="https://user-images.githubusercontent.com/8313529/155194874-3799d2fb-327b-4f40-afe0-4024973eb364.png">

The expected behavior of this component is to work with dynamic data as the same hardcoded data does.
It's important to check the reason why the selected value is not being updated and fix it to update whenever the `options` list changes.

Here is a print to remember how the [Dropdown](https://gympass.github.io/yoga/components/dropdown) component is:
<img width="667" alt="Screen Shot 2022-02-22 at 15 27 05" src="https://user-images.githubusercontent.com/8313529/155195627-154acd2c-cf25-46ce-bfb0-f629c727ebc8.png">

**Comment by sailemarinho** [comment]
I'm facing the same issue!
Up!
