### ISSUE TITLE
[BUG] yoga-system examples are broken

### ISSUE THREAD

**Issue by caiotracera** [Gympass/yoga#450]
**Describe the bug**
I was reading the official documentation about the `@gympass/yoga-system`, and found out that the CodeSandboxes's examples are broken, 'cause they are missing the `@gympass/yoga-system` dependency.

**To Reproduce**
1. Go to the official documentation on https://gympass.github.io/yoga/system/getting-started
2. Choose any item from the menu. In this case, I'll choose the `backgroundColor`.
3. Click on the `CodeSandbox` icon to open the code.
4. Neither the `@gympass/yoga-system` dependency is listed on the `package.json` nor being imported in the file.

**Screenshots**

![Captura de Tela 2022-03-26 às 22 12 39](https://user-images.githubusercontent.com/25802240/160262466-0985a08f-d0cc-4b6e-a1eb-0361f3aa6790.png)

**Desktop (please complete the following information):**
 - OS: macOS Monterey (12.2.1)
 - Browser: Brave
 - Version: 1.36.119

**Additional context**
* After adding the `@gympass/yoga-system` to the dependency list, the examples became to work as expected. Working example: https://codesandbox.io/s/reverent-visvesvaraya-jn4ghk?file=/index.js

**Comment by mmartinsoliv** [comment]
Hello, @caiotracera! Thanks for the bug notice.
