### ISSUE TITLE
[FEAT] Remove moment lib from Datepicker

### ISSUE THREAD

**Issue by frgiovanna** [gympass/yoga#543]
**Is your feature request related to a problem? Please describe.**

The Datepicker component is using the `moment` library as a dependency. This lib was deprecated and its own [documentation](https://momentjs.com/) gives advice to finding another lib to do the same as it does.  
 <br>

**Describe alternatives you've considered**

We can use the [date-fns](https://date-fns.org/) lib, which is a great and well-maintained one, and use its `format` function the same way we're doing with the `moment`.

On the [Datepicker](https://github.com/Gympass/yoga/blob/master/packages/yoga/src/Datepicker/web/Datepicker.jsx#L245) component:
```javascript
import { format } from 'date-fns';

// ...

  return (
      startD && (
        <Input disabled={disabled}>
          {format(startD, dateFormat)}
          {endD && ` - ${format(endD, dateFormat)}`}
        </Input>
      )
    );
```

**Comment by caiotracera** [comment]
Hey, @frgiovanna!
I think it's a great idea! Do you feel comfortable to make this change and create the PR?
