### ISSUE TITLE
[BUG] Handle localization on Datepicker component

### ISSUE THREAD

**Issue by caiotracera** [gympass/yoga#550]
**Describe the bug**
As reported by @frgiovanna in https://github.com/gympass/yoga/pull/548#discussion_r963946358, the `DatePicker` component exports a fixed date format that might not meet the user's localization on the platform.

**Expected behavior**
The component should consider the user's localization to determine the format of the date that will be rendered.

**Comment by ricardomcruz** [comment]
Hello, there is some update regarding this issue?
Today i found this same bug, i came here to raise the issue but it seems that it has described already for some months:

cc: @RodrigoMeloMarcolino

**Comment by caiotracera** [comment]
Hey, @ricardomcruz!
We are discussing possible fixes for this on #626.
