### ISSUE TITLE
[BUG] Plancard has the wrong background color

### ISSUE THREAD

**Issue by alan-oliv** [Gympass/yoga#73]
**Describe the bug**
PlanCard appears to use the wrong background color.

**Expected behavior**
The expected background color is 75% of secondary, and not 100%

**Screenshots**
![image](https://user-images.githubusercontent.com/4368481/71898149-58bd8880-3137-11ea-8019-265af025abe0.png)

**Comment by victormath12** [comment]
closed by #76
