### ISSUE TITLE
[BUG] New icons doesn't render nice with `fill` prop

### ISSUE THREAD

**Issue by aly-lopes** [gympass/yoga#785]
**Describe the bug**
The new icons (`Attention`, `Delayed`, `Information`, `Success`) doesn't render correctly when the `fill` prop is provided.

**To Reproduce**
1. Go to `packages/labnative/pages/Icon.jsx`
2. Change Icon to one of the mentioned above

**Expected behavior**
I think these icons should just ignore the fill prop **or** apply it correctly.

**Screenshots**
In these screenshots, the `fill` prop is provided with value `feedback.success.dark`.

| Attention | Delayed | Information | Success |
| --------- | -------- | ----------- | --------- |
| <img src="https://github.com/gympass/yoga/assets/152918348/b860e8d4-ac30-4274-aa89-5cb71a485394" width="200" /> | <img src="https://github.com/gympass/yoga/assets/152918348/6a7099c8-6a8b-4de0-bb3f-a99f80f69a25" width="200" /> | <img src="https://github.com/gympass/yoga/assets/152918348/cd577e91-202a-4cb3-9164-8bd5781d6bc2" width="200" /> | <img src="https://github.com/gympass/yoga/assets/152918348/a5d6a610-2291-4287-8f53-b9d2e5a1f4d9" width="200" /> |

**Comment by evilamaior** [comment]
Hey @aly-lopes, thanks for reporting. This issue was [resolved in this PR](https://github.com/gympass/yoga/pull/786).

**Comment by evilamaior** [comment]
Hey @aly-lopes, thanks for reporting. This issue was [resolved in this PR](https://github.com/gympass/yoga/pull/786).
