### ISSUE TITLE
[BUG] Wrong component on docs (Button)

### ISSUE THREAD

**Issue by tcK1** [Gympass/yoga#98]
**Describe the bug**
We are showing the Input component on the Button.Default docs page.

**To Reproduce**
1. Go to https://gympass.github.io/yoga/components/button/default
2. See error

**Expected behavior**
Should show the Button component.

**Screenshots**
![image](https://user-images.githubusercontent.com/9873486/74355457-ac0ca180-4d9b-11ea-9cc3-5ecb63f800cc.png)

**Comment by allyssonsantos** [comment]
@tcK1 fixed by #99
